version: "3.8"

services:
  localstack:
    image: localstack/localstack
    profiles: ["prod", "dev"]
    ports:
      - "4566:4566"            # LocalStack Gateway
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - SERVICES=s3,cloudwatch
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  app:
    build: .
    command: npm run test
    profiles: ["dev"]
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - ACCESS_KEY_ID=${ACCESS_KEY_ID}
      - SECRET_ACCESS_KEY=${SECRET_ACCESS_KEY}
      - REGION=${REGION}
      - ENDPOINT=${ENDPOINT}
    depends_on:
      - localstack