service: my-bucket-manager
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-offline
