service: my-bucket-manager
frameworkVersion: '3'
	
useDotenv: true
provider:
  name: aws
  runtime: nodejs20.x

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi:
          path: /
          method: get
environment:
  ACCESS_KEY_ID: ${env:ACCESS_KEY_ID}
  SECRET_ACCESS_KEY: ${env:SECRET_ACCESS_KEY}
  REGION: ${env:REGION}
  ENDPOINT: ${env:ENDPOINT}

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
