name: Docker Compose Actions Workflow
on:
  push:
    paths:
      - '**.js'
      - '**.json'
      - '**.yml'
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  REGION: ${{ secrets.REGION }}
  ENDPOINT: ${{ secrets.ENDPOINT }}
  ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
  SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose --profile dev up
      - name: Clean up
        run: docker-compose down --volumes