name: Docker Compose Actions Workflow
on:
  push:
    paths:
      - '**.js'
      - '**.json'
      - '**.yml'
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  REGION: ${{ secrets.REGION }}
  ENDPOINT: ${{ secrets.ENDPOINT }}
  ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
  SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}

jobs:
  setup-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose --profile prod up -d
      
      - name: Create .env
        uses: ozaytsev86/create-env-file@v1
        with:
          ENV_REGION: ${{ secrets.REGION }}
          ENV_ENDPOINT: ${{ secrets.ENDPOINT }}
          ENV_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          ENV_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
      
      - name: Run tests
        uses: actions/setup-node@v4
        with:
          node-version: 20
        run: npm ci --silent
        run: npm run test

      - name: Clean up
        run: docker-compose down --volumes